name: CI dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu    # "ubuntu" is a more generic container
    # container: pandoc/latex    # "ubuntu" is a more generic container
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
    steps:
      - uses: actions/checkout@v2
      - name: creates output        
        env:
          BRANCHSELECTION: 'dev'
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          #SECRET_TEST: ${{ secrets.SECRET_TEST }}
        run:  sh ./.github/workflows/build.sh # some command from your repository that creates
                            # output to "source-directory" ("output" in the example)
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          # API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'output_temp'
          destination-github-username: 'ChaosRifle'
          destination-repository-name: 'ChaosTheory'
          user-email: nil
          target-branch: dev
